workspace:
  path: /data

registry:
  - name: pacman
    settings:
      auto_tag: true
      dockerfile: "./Dockerfile"
    when:
      event:
        - push
        - tag

deploy:
  - name: development
    image: pacman
    tag: latest
